spring.application.name=proxy-oauth
server.port=9090

# OAuth2 Client Configuration
oauth.client.url=http://localhost:8080/realms/myrealm/protocol/openid-connect/token
#https://oauth-server.example.com/oauth/token
oauth.client.attempts=3
oauth.client.timeout=15000

# WebClient Configuration
webclient.max-connections=500
webclient.connection-timeout=5000
webclient.read-timeout=10000
webclient.write-timeout=10000

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
